// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
